development:
  adapter: mysql2
  database: apolon_dev
  username: fork
  password: password
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: apolon_test
  username: fork
  password: password
  pool: 5
  timeout: 5000
